# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowKursacha.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(1000, 800))
        MainWindow.setBaseSize(QtCore.QSize(1000, 600))
        MainWindow.setStyleSheet("\n"
"\n"
"background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0852273 rgba(129, 0, 156, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 12pt \"Fixedsys\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AccidentsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AccidentsBtn.setGeometry(QtCore.QRect(400, 180, 151, 31))
        self.AccidentsBtn.setStyleSheet("background-color: rgb(61, 255, 255);\n"
"border-radius: 5px;")
        self.AccidentsBtn.setObjectName("AccidentsBtn")
        self.DriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DriversBtn.setGeometry(QtCore.QRect(400, 220, 151, 31))
        self.DriversBtn.setStyleSheet("background-color: rgb(61, 255, 255);\n"
"border-radius: 5px;")
        self.DriversBtn.setObjectName("DriversBtn")
        self.FuelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FuelBtn.setGeometry(QtCore.QRect(400, 260, 151, 31))
        self.FuelBtn.setStyleSheet("background-color: rgb(61, 255, 255);\n"
"border-radius: 5px;")
        self.FuelBtn.setObjectName("FuelBtn")
        self.InspectionsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.InspectionsBtn.setGeometry(QtCore.QRect(400, 300, 151, 31))
        self.InspectionsBtn.setStyleSheet("background-color: rgb(61, 255, 255);\n"
"border-radius: 5px;")
        self.InspectionsBtn.setObjectName("InspectionsBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vehicles"))
        self.AccidentsBtn.setText(_translate("MainWindow", "DepositTypeMapping"))
        self.DriversBtn.setText(_translate("MainWindow", "DepositTypes"))
        self.FuelBtn.setText(_translate("MainWindow", "Deposits"))
        self.InspectionsBtn.setText(_translate("MainWindow", "Investors"))
